name: Deploy to GCP App Engine (Challenge Chapter 5)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate env from secrets
        # working-directory: ./chapter-5/topic-1
        run: |
          SECRETS="${{ secrets.CHALLENGE_CHAPTER_5_GCP_ENV }}"
          echo "$SECRETS" | tr ';' '\n' >> .env

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.CHALLENGE_CHAPTER_5_GCP_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Deploy to App Engine
        # working-directory: ./chapter-5/topic-1
        run: |
          gcloud app deploy app.yaml --quiet
